### ISSUE TITLE
Show usage information on landing

### ISSUE THREAD

**Issue by Satont** [waifuvault/WaifuVault#106]
Might be insteresting (atleast for me) to see how many files uploaded, how many size all files have.

**Comment by VictoriqueMoe** [comment]
you mean publically? you can see this if you login and go to admin section for stats for example:
![image](https://github.com/waifuvault/WaifuVault/assets/27996712/2fa291db-933c-403a-bbce-bf2f344ac8bf)

**Comment by Satont** [comment]
> you mean publically?

Yep.

**Comment by VictoriqueMoe** [comment]
> > you mean publically?
> 
> Yep.

sounds good to me. @nakedmcse can you add a section on the front page that tells these 2 stats?

something like "serving x files publically totalling xMB/GB"?

**Comment by nakedmcse** [comment]
Sure I'll do that

**Comment by weddleben** [comment]
@VictoriqueMoe  any chance you'd like to share a tip on how to call the `/socket.io/recordInfo/` endpoint? I can't figure it out. can you ONLY call it with JS in a browser?

**Comment by nakedmcse** [comment]
Its a standard socket.io connection, so anything that supports the protocol should work just fine.

Here it is in Python:
https://github.com/nakedmcse/PyRandoStuff/blob/master/wsockets.py

https://x.com/nakedMCSE/status/1876862822480478640

**Comment by VictoriqueMoe** [comment]
> @VictoriqueMoe any chance you'd like to share a tip on how to call the `/socket.io/recordInfo/` endpoint? I can't figure it out. can you ONLY call it with JS in a browser?

@weddleben it's a websocket connection. thne WS namespace is `recordInfo` but do not reccomend trying to connect to this due to the fact that the websocket uses CORS and will reject your connection attempt if you do not originate from the origin

**Comment by VictoriqueMoe** [comment]
you are also welcome to open a [discussion ](https://github.com/orgs/waifuvault/discussions) about this

**Comment by weddleben** [comment]
Thank you both! Inadvertently continued this discussion on twitter. And sorry, I won't again start discussions via ancient closed issues!
