### ISSUE TITLE
remove redundant fetch dep

### ISSUE THREAD

**Issue by Satont** [waifuvault/WaifuVault#108]
https://github.com/waifuvault/WaifuVault/blob/afaed7c58b0df2ebfb770f232789a0d532fb1284/package.json#L73

Nodejs since version 16 or 18 has `fetch` out of the box as global. What purpose of dependency?

**Comment by VictoriqueMoe** [comment]
> https://github.com/waifuvault/WaifuVault/blob/afaed7c58b0df2ebfb770f232789a0d532fb1284/package.json#L73
> 
> Nodejs since version 16 or 18 has `fetch` out of the box as global. What purpose of dependency?

Yeh, you are right, the Node SDK makes use of the built in fetch. the reason i used this was that it was there from my template. I always meant to remove it but keep forgetting
