### ISSUE TITLE
remove npx from scripts

### ISSUE THREAD

**Issue by Satont** [waifuvault/WaifuVault#109]
https://github.com/waifuvault/WaifuVault/blob/afaed7c58b0df2ebfb770f232789a0d532fb1284/package.json#L7

There no point to use `npx` for each binary in `package.json`, because they automatically resolved to project `node_modules`. So `npx` can be omitted in `package.json`

**Comment by VictoriqueMoe** [comment]
> https://github.com/waifuvault/WaifuVault/blob/afaed7c58b0df2ebfb770f232789a0d532fb1284/package.json#L7
> 
> There no point to use `npx` for each binary in `package.json`, because they automatically resolved to project `node_modules`. So `npx` can be omitted in `package.json`

fair point.
